export default class Images {
  constructor(){}
  getData() { 
    return[
        {
          "puzzle":{
            "folder": "img1",
            "images":
            [
              "image_part_001",
              "image_part_002",
              "image_part_003",
              "image_part_004",
              "image_part_005",
              "image_part_006",
              "image_part_007",
              "image_part_008",
              "image_part_009",
              "image_part_010",
              "image_part_011",
              "image_part_012",
              "image_part_013",
              "image_part_014",
              "image_part_015",
              "image_part_016",
              "image_part_017",
              "image_part_018",
              "image_part_019",
              "image_part_020",
              "image_part_021",
              "image_part_022",
              "image_part_023",
              "image_part_024",
              "image_part_025",
              "image_part_026",
              "image_part_027",
              "image_part_028",
              "image_part_029",
              "image_part_030"
            ]
          }
        },
        {
          "puzzle":{
            "folder": "img2",
            "images":
            [
              "image_part_001",
              "image_part_002",
              "image_part_003",
              "image_part_004",
              "image_part_005",
              "image_part_006",
              "image_part_007",
              "image_part_008",
              "image_part_009",
              "image_part_010",
              "image_part_011",
              "image_part_012",
              "image_part_013",
              "image_part_014",
              "image_part_015",
              "image_part_016",
              "image_part_017",
              "image_part_018",
              "image_part_019",
              "image_part_020",
              "image_part_021",
              "image_part_022",
              "image_part_023",
              "image_part_024",
              "image_part_025",
              "image_part_026",
              "image_part_027",
              "image_part_028",
              "image_part_029",
              "image_part_030"
            ]
          }
        },
        {
          "puzzle":{
            "folder": "img3",
            "images":
            [
              "image_part_001",
              "image_part_002",
              "image_part_003",
              "image_part_004",
              "image_part_005",
              "image_part_006",
              "image_part_007",
              "image_part_008",
              "image_part_009",
              "image_part_010",
              "image_part_011",
              "image_part_012",
              "image_part_013",
              "image_part_014",
              "image_part_015",
              "image_part_016",
              "image_part_017",
              "image_part_018",
              "image_part_019",
              "image_part_020",
              "image_part_021",
              "image_part_022",
              "image_part_023",
              "image_part_024",
              "image_part_025",
              "image_part_026",
              "image_part_027",
              "image_part_028",
              "image_part_029",
              "image_part_030"
            ]
          }
        },
        {
          "puzzle":{
            "folder": "img4",
            "images":
            [
              "image_part_001",
              "image_part_002",
              "image_part_003",
              "image_part_004",
              "image_part_005",
              "image_part_006",
              "image_part_007",
              "image_part_008",
              "image_part_009",
              "image_part_010",
              "image_part_011",
              "image_part_012",
              "image_part_013",
              "image_part_014",
              "image_part_015",
              "image_part_016",
              "image_part_017",
              "image_part_018",
              "image_part_019",
              "image_part_020",
              "image_part_021",
              "image_part_022",
              "image_part_023",
              "image_part_024",
              "image_part_025",
              "image_part_026",
              "image_part_027",
              "image_part_028",
              "image_part_029",
              "image_part_030"
            ]
          }
        }
      ]
  }
}
